Update to use Socket Mode as default
slackapi/bolt-js-getting-started-app pull request #4
Opened 2021-07-15 04:40 UTC by srajiang

###  Summary

Related to:
* Sibling changes in sample Bolt Python project: https://github.com/slackapi/bolt-python-getting-started-app/pull/1
* Related changes in Bolt for JS Getting Started documentation: https://github.com/slackapi/bolt-js/pull/990

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-js-getting-started-app/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2021-08-03 16:25 UTC, mwbrooks requested changes
Looks good @srajiang!

I noticed that you have two copies of the same app - `app.js` (Socket Mode) and `app_http.js` (Request URL).

My concern is that our guides will drift apart and one (likely the `app_http.js`) will become out-of-date.

Do you think it would be better to only have `app.js`? The _Deploying to AWS Lambda Guide_ could add a step to disable Socket Mode. This is also a good education opportunity, since we may have developers who try to use Socket Mode on a Lambda-like deployment (which won't work).

2021-08-03 16:26 UTC, mwbrooks commented
We'll also want to bump the version (major?) when we merge this PR https://github.com/slackapi/bolt-js-getting-started-app/tags

2021-08-04 20:19 UTC, srajiang commented
@mwbrooks - I've updated the PR to include just the single `app.py` file w/ SocketMode as default + bumped the version.

2021-08-04 23:22 UTC, mwbrooks approved these changes
🎉 Yay! Thanks for giving the guides/template some ❤️ and updating them to Socket Mode!

2021-08-04 23:22 UTC, mwbrooks commented on .github/maintainers_guide.md
> +When making changes to this repo, it's also important to keep all of our other guides and apps up-to-date.
Nice! 👌🏻

2021-08-04 23:23 UTC, mwbrooks commented
After merging, we'll want to throw a tag on the commit as well!

2021-08-04 23:57 UTC, merged